name: Aspendos ISO Yapici
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Al
        uses: actions/checkout@v4

      - name: Sistemi Hazirla
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build

      - name: Aspendos Klasorlerini Olustur
        run: |
          mkdir -p build && cd build
          lb config --binary-images iso-hybrid --architectures amd64 --debian-installer live
          mkdir -p config/package-lists
          echo "gnome-core firefox-esr network-manager" > config/package-lists/my.list.chroot

      - name: ISOyu Derle
        run: |
          cd build
          sudo lb build

      - name: ISOyu Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Aspendos-OS-ISO
          path: build/*.iso
