name: Aspendos OS Insaat
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Araclari Yukle
        run: sudo apt-get update && sudo apt-get install -y live-build

      - name: ISOyu Olustur
        run: |
          mkdir build && cd build
          lb config --binary-images iso-hybrid --architectures amd64
          sudo lb build

      - name: ISOyu Bize Ver
        uses: actions/upload-artifact@v3
        with:
          name: Aspendos-OS-Dosyasi
          path: build/*.iso
